# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|


  # Box Settings
  config.vm.box = "ubuntu/trusty64"

  # Network Settings
  config.vm.network "private_network", ip: "192.168.33.10"

  # Provision
  config.vm.provision "shell", path: "bootstrap.sh"

  # Folder Settings
  config.vm.synced_folder ".", "/var/www"
  # config.vm.synced_folder ".", "/var/www/", :mount_options => ["dmode=777", "fmode=666"]
  # config.vm.synced_folder ".", "/var/www/", :owner=> 'www-data', :group=>'root' #group=>'www-data'
  # config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777", "fmode=666"] }


end
